<?php
namespace app\mshop\controller;
vendor('wxpay.lib.WxPayApi');
vendor('wxpay.JsApiPay');
class Pay extends Index
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $user = session('user_wechat_login');
        $this->assign('user',$user);
    }

    /**
     * 组合统一下单接口数据
     * @return mixed
     */
    public function index(){
        $tools = new \JsApiPay();
        $openId = $tools->GetOpenid();

        //②、统一下单
        $input = new \WxPayUnifiedOrder();
        $input->SetBody("test");
        $input->SetAttach("test");
        $input->SetOut_trade_no(\WxPayConfig::MCHID.date("YmdHis"));
        $input->SetTotal_fee("1");
        $input->SetTime_start(date("YmdHis"));
        $input->SetTime_expire(date("YmdHis", time() + 600));
        $input->SetGoods_tag("test");
        $input->SetNotify_url("http://".request()->host().url('mshop/notify/index'));
        $input->SetTrade_type("JSAPI");
        $input->SetOpenid($openId);
        $order = \WxPayApi::unifiedOrder($input);
        $jsApiParameters = $tools->GetJsApiParameters($order);

        //获取共享收货地址js函数参数
        $editAddress = $tools->GetEditAddressParameters();
        $this->assign('jsApiParameters',$jsApiParameters);
        $this->assign('editAddress',$editAddress);
        return $this->fetch();
    }

    public function create_order(){
        $data= input('post.');
        $user = get_uerinfo();
        if(!$user){
            $this->result('please login',403,'请您先登录授权');
        }
        $order = [
            'out_trade_on' => orderNo(),
            'openid'    =>  $user['openid'],
            'goods_id' => $data['goods_id'],
            'spec_id'   =>  $data['spec'],
            'dateline' =>time(),
            'fee'   =>  $data['price'],
            'num' => $data['num'],
            'total_fee' => $data['price'] * $data['num'],
            'trade_state' =>1
        ];
        $status = db('shop_order')->insert($order);
        if($status){
            $this->result('success',200,'订单创建成功');
        }else{
            $this->result('error',500,'订单创建失败！');
        }

    }
    public function create_many_order(){
        $data = input('post.');
        $user = get_uerinfo();
        print_r($data);
    }
    public function calator_cart(){
        $data = input('get.');
        foreach ($data as $item=>$value){
            if(!isset($value['id'])){
                unset($data[$item]);
            }
        }
        $total_fee = 0;
        foreach ($data as $item=>$value){
            $total_fee  = $total_fee + $value['price']*$value['num'];
        }
        return $total_fee;
    }
    public function notify(){
        echo 'SUCCESS';
    }
}
