<?php
namespace app\mshop\controller;

use app\common\controller\Weixin;
use app\common\model\ShopOrder;

class User extends Index
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $user = session('user_wechat_login');
        $this->assign('user',$user);
    }

    public function index()
    {
        return $this->fetch();
    }

    /**
     * 微信授权登录
     */
    public function wechat_auth(){
        $weixin = new Weixin();
        $weixin->authorize();
    }

    /**
     * 订单列表
     * @return mixed
     */
    public function order(){
        $status = input('get.status','all');
        $list = ShopOrder::datalist($status);
        $this->assign('list',$list);
        $this->assign('status',$status);
        return $this->fetch();
    }

    public function myticket(){
        return $this->fetch();
    }
    public function address(){
        $user = get_uerinfo();
        if(request()->isPost()){
            $data =input('post.');
            $data['openid'] = $user['openid'];
            $status = db('user_wechat_address')->insert($data);
            if($status){
                cache('user_address',null);
                $this->result('ok',200,'地址添加成功');
            }else{
                $this->result('error',500,'内部服务器错误，请联系管理员');
            }
        }
        $address = cache('user_address');
        if(!$address){
            $address = db('user_wechat_address')->where('openid',$user['openid'])->select();
            cache('user_address',$address,0);
        }
        $this->assign('address',$address);
        return $this->fetch();
    }
}
